/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DOCENTES;

import PRINCIPALES.temas_principales;
import java.awt.Dimension;

/**
 *
 * @author Anahí Zepeda
 */
public class migrupo_listas extends javax.swing.JFrame {

    /**
     * Creates new form migrupo_materialdeapoyo
     */
    public migrupo_listas() {
        initComponents();
        this.setSize(new Dimension(700, 400));
           setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        atras2 = new javax.swing.JButton();
        adelante = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        propietario2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setText("MI GRUPO");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(360, 10, 180, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Secundaria. 1°");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(450, 80, 90, 15);

        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jPanel2.add(jButton12);
        jButton12.setBounds(320, 110, 130, 100);

        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jPanel2.add(jButton14);
        jButton14.setBounds(320, 110, 130, 100);

        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);
        jButton15.setBounds(0, 290, 110, 110);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir chico.png"))); // NOI18N
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir chico.png"))); // NOI18N
        salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir mediano.png"))); // NOI18N
        salir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir mediano.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel2.add(salir);
        salir.setBounds(0, 0, 100, 100);

        atras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/atras chico.png"))); // NOI18N
        atras2.setBorderPainted(false);
        atras2.setContentAreaFilled(false);
        atras2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/atras chico.png"))); // NOI18N
        atras2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/atras mediano.png"))); // NOI18N
        atras2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/atras mediano.png"))); // NOI18N
        atras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras2ActionPerformed(evt);
            }
        });
        jPanel2.add(atras2);
        atras2.setBounds(160, 0, 100, 100);

        adelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/derecha chico.png"))); // NOI18N
        adelante.setBorderPainted(false);
        adelante.setContentAreaFilled(false);
        adelante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adelante.setEnabled(false);
        adelante.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/derecha chico.png"))); // NOI18N
        adelante.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/derecha mediano.png"))); // NOI18N
        adelante.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/derecha mediano.png"))); // NOI18N
        jPanel2.add(adelante);
        adelante.setBounds(240, 0, 120, 100);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/home chico.png"))); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/home chico.png"))); // NOI18N
        jButton22.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/home mediano.png"))); // NOI18N
        jButton22.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/home mediano.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton22);
        jButton22.setBounds(70, 0, 110, 100);

        propietario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/simbolo chico t.png"))); // NOI18N
        propietario2.setBorderPainted(false);
        propietario2.setContentAreaFilled(false);
        propietario2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(propietario2);
        propietario2.setBounds(560, 0, 120, 100);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setText("LISTAS");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(370, 50, 180, 29);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText(" LISTA DE ASISTENCIA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 150, 230, 22);

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setText("GENERAR");
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 250, 110, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText(" LISTA DE ACTIVIDADES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 150, 240, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"A\"", "\"B\"", "\"C\"", "\"D\"" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(430, 200, 147, 30);

        jButton2.setBackground(new java.awt.Color(255, 204, 255));
        jButton2.setText("GENERAR");
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 250, 110, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("GRUPO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 200, 70, 15);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"A\"", "\"B\"", "\"C\"", "\"D\"" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(170, 200, 147, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("GRUPO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 200, 70, 15);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/FONDO DEGRADADO.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, 0, 700, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void atras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras2ActionPerformed
        mi_grupo t = new mi_grupo();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_atras2ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        temas_principales t = new temas_principales();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton22ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adelante;
    private javax.swing.JButton atras2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton propietario2;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
