/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DOCENTES;

import PRINCIPALES.temas_principales;
import java.awt.Dimension;

/**
 *
 * @author Anahí Zepeda
 */
public class migrupo_evaluaciones extends javax.swing.JFrame {

    /**
     * Creates new form migrupo_evaluaciones
     */
    public migrupo_evaluaciones() {
        initComponents();
         this.setSize(new Dimension(2190, 1000));
        //setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        atras2 = new javax.swing.JButton();
        adelante = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        propietario2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setText("MI GRUPO");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(500, 10, 180, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Secundaria. 1°");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(930, 70, 90, 15);

        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jPanel2.add(jButton12);
        jButton12.setBounds(320, 110, 130, 100);

        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jPanel2.add(jButton14);
        jButton14.setBounds(320, 110, 130, 100);

        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);
        jButton15.setBounds(0, 290, 110, 110);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir chico.png"))); // NOI18N
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir chico.png"))); // NOI18N
        salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir mediano.png"))); // NOI18N
        salir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir mediano.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel2.add(salir);
        salir.setBounds(0, 0, 100, 100);

        atras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/atras chico.png"))); // NOI18N
        atras2.setBorderPainted(false);
        atras2.setContentAreaFilled(false);
        atras2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/atras chico.png"))); // NOI18N
        atras2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/atras mediano.png"))); // NOI18N
        atras2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/atras mediano.png"))); // NOI18N
        atras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras2ActionPerformed(evt);
            }
        });
        jPanel2.add(atras2);
        atras2.setBounds(160, 0, 100, 100);

        adelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/derecha chico.png"))); // NOI18N
        adelante.setBorderPainted(false);
        adelante.setContentAreaFilled(false);
        adelante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adelante.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/derecha chico.png"))); // NOI18N
        adelante.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/derecha mediano.png"))); // NOI18N
        adelante.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/derecha mediano.png"))); // NOI18N
        jPanel2.add(adelante);
        adelante.setBounds(240, 0, 120, 100);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/home chico.png"))); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/home chico.png"))); // NOI18N
        jButton22.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/home mediano.png"))); // NOI18N
        jButton22.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/home mediano.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton22);
        jButton22.setBounds(70, 0, 110, 100);

        propietario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/simbolo chico t.png"))); // NOI18N
        propietario2.setBorderPainted(false);
        propietario2.setContentAreaFilled(false);
        propietario2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(propietario2);
        propietario2.setBounds(1220, 0, 120, 100);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setText("EVALUACIONES");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(690, 40, 210, 29);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 100);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GEOMETRIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setText("Gráficas circulares");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 290, 240, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 30, 65, 41);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 30, 65, 41);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 80, 65, 41);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton4);
        jButton4.setBounds(80, 80, 65, 41);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 130, 65, 41);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton6);
        jButton6.setBounds(80, 130, 65, 41);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton7);
        jButton7.setBounds(10, 180, 65, 41);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton8);
        jButton8.setBounds(80, 180, 65, 41);

        jLabel2.setText("Introducción a la geometría");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 40, 260, 14);

        jLabel3.setText("Areas y perímetros");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 90, 270, 14);

        jLabel4.setText("Teorema de pitágoras");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 140, 270, 14);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton9);
        jButton9.setBounds(10, 230, 65, 41);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton10);
        jButton10.setBounds(80, 230, 65, 41);

        jLabel5.setText("Triangulos y cuadriláteros");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 190, 240, 14);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jPanel1.add(jButton11);
        jButton11.setBounds(10, 230, 65, 41);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jPanel1.add(jButton13);
        jButton13.setBounds(80, 230, 65, 41);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton16);
        jButton16.setBounds(10, 280, 65, 41);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton17);
        jButton17.setBounds(80, 280, 65, 41);

        jLabel7.setText("Medidas de volumen y capacidad");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 240, 240, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(910, 120, 440, 340);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALGEBRA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel6.setText("Relaciones");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(160, 290, 240, 14);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton18);
        jButton18.setBounds(80, 30, 65, 41);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton19);
        jButton19.setBounds(10, 30, 65, 41);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton20);
        jButton20.setBounds(10, 80, 65, 41);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton21);
        jButton21.setBounds(80, 80, 65, 41);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton23);
        jButton23.setBounds(10, 130, 65, 41);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton24);
        jButton24.setBounds(80, 130, 65, 41);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton25);
        jButton25.setBounds(10, 180, 65, 41);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton26);
        jButton26.setBounds(80, 180, 65, 41);

        jLabel11.setText("Operaciones con términos semejantes");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(160, 40, 260, 14);

        jLabel12.setText("Ecuaciones de primer grado");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(160, 90, 270, 14);

        jLabel13.setText("Sistema de ecuaciones lineales");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(160, 140, 270, 14);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton27);
        jButton27.setBounds(10, 230, 65, 41);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton28);
        jButton28.setBounds(80, 230, 65, 41);

        jLabel14.setText("Sistema cartesiano o plano cartesiano");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(160, 190, 240, 14);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jPanel3.add(jButton29);
        jButton29.setBounds(10, 230, 65, 41);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jPanel3.add(jButton30);
        jButton30.setBounds(80, 230, 65, 41);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton31);
        jButton31.setBounds(10, 280, 65, 41);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton32);
        jButton32.setBounds(80, 280, 65, 41);

        jLabel15.setText("Funciones");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(160, 240, 240, 14);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(470, 120, 440, 340);

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ARITMETICA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel7.setLayout(null);

        jLabel34.setText("Sucesiones aritméticas");
        jPanel7.add(jLabel34);
        jLabel34.setBounds(160, 290, 240, 14);

        jButton75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton75.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton75);
        jButton75.setBounds(80, 30, 65, 41);

        jButton76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton76.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton76);
        jButton76.setBounds(10, 30, 65, 41);

        jButton77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton77.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton77);
        jButton77.setBounds(10, 80, 65, 41);

        jButton78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton78.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton78);
        jButton78.setBounds(80, 80, 65, 41);

        jButton79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton79.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton79);
        jButton79.setBounds(10, 130, 65, 41);

        jButton80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton80.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton80);
        jButton80.setBounds(80, 130, 65, 41);

        jButton81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton81.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton81);
        jButton81.setBounds(10, 180, 65, 41);

        jButton82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton82.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton82);
        jButton82.setBounds(80, 180, 65, 41);

        jLabel35.setText("Conversión entre fracciones y decimales");
        jPanel7.add(jLabel35);
        jLabel35.setBounds(160, 40, 280, 14);

        jLabel36.setText("Problemas aditivos con números positivos y negativos");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(160, 90, 360, 14);

        jLabel37.setText("Problemas multiplicativos de fracciones y decimales");
        jPanel7.add(jLabel37);
        jLabel37.setBounds(160, 140, 360, 14);

        jButton83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton83.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton83);
        jButton83.setBounds(10, 230, 65, 41);

        jButton84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton84.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton84);
        jButton84.setBounds(80, 230, 65, 41);

        jLabel38.setText("Problemas de porcentaje");
        jPanel7.add(jLabel38);
        jLabel38.setBounds(160, 190, 240, 14);

        jButton85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jPanel7.add(jButton85);
        jButton85.setBounds(10, 230, 65, 41);

        jButton86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jPanel7.add(jButton86);
        jButton86.setBounds(80, 230, 65, 41);

        jButton87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/word 32.png"))); // NOI18N
        jButton87.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton87);
        jButton87.setBounds(10, 280, 65, 41);

        jButton88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pdf 32.png"))); // NOI18N
        jButton88.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton88);
        jButton88.setBounds(80, 280, 65, 41);

        jLabel39.setText("Jerarquía de las operaciones");
        jPanel7.add(jLabel39);
        jLabel39.setBounds(160, 240, 240, 14);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 120, 470, 340);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/FONDO EVALUACIONES(2).png"))); // NOI18N
        getContentPane().add(jLabel40);
        jLabel40.setBounds(0, 0, 1380, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void atras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras2ActionPerformed
        mi_grupo t = new mi_grupo();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_atras2ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        temas_principales t = new temas_principales();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton22ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adelante;
    private javax.swing.JButton atras2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton propietario2;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
