/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRINCIPALES;

import DOCENTES.Conexion2;
import DOCENTES.REGISTRARSE_DOCENTE;
import java.awt.Dimension;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import BD_CONEXION.Docente;

/**
 *
 * @author Anahí Zepeda
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    private String UserDefault="ADMIN",PassDefault="VENUS";
    Conexion2 Conect;
    DefaultTableModel modelo;
    String campoconsulta;
    int usuarios;
    String usuario;
    String contraseña;
    
    
    public login() {
        initComponents();
        this.setSize(new Dimension(430, 400));
        setLocationRelativeTo(null);
        dispose();
        txtUsuario.requestFocus();
        //primeraCarga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        vamos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        propietario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CONTRASEÑA:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 190, 131, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("USUARIO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 150, 92, 22);
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(170, 190, 170, 30);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(170, 140, 170, 30);

        salir.setBackground(new java.awt.Color(102, 0, 102));
        salir.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir chico.png"))); // NOI18N
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir chico.png"))); // NOI18N
        salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir grande.png"))); // NOI18N
        salir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir grande.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(0, 240, 100, 102);

        vamos.setBackground(new java.awt.Color(102, 0, 102));
        vamos.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        vamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/inicia chico.png"))); // NOI18N
        vamos.setBorderPainted(false);
        vamos.setContentAreaFilled(false);
        vamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vamos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/inicia chico.png"))); // NOI18N
        vamos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/inicia mediano.png"))); // NOI18N
        vamos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/inicia mediano.png"))); // NOI18N
        vamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vamosMousePressed(evt);
            }
        });
        vamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vamosActionPerformed(evt);
            }
        });
        getContentPane().add(vamos);
        vamos.setBounds(260, 230, 130, 120);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/USER.png"))); // NOI18N
        jButton1.setText("REGISTRARSE");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/USER.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/USER3.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/USER3.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 250, 200, 90);

        jPanel1.setOpaque(false);

        propietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/simbolo chico t.png"))); // NOI18N
        propietario.setBorderPainted(false);
        propietario.setContentAreaFilled(false);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setText("INICIAR SESION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 429, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/FONDO DEGRADADO 3.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 430, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void vamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vamosActionPerformed
         
      /*  String user = txtUsuario.getText();
        String pass = txtContraseña.getText();
        
        try { 
            Conect = new Conexion2();
            
            if(usuarios<1){
                showMessageDialog(null,"No hay Usuarios");
                txtContraseña.setText("");
                txtUsuario.setText("");
            }
            
            if (user.equals(Conect)==pass.equals(Conect)){
                 temas_principales t= new temas_principales();
                 t.setVisible(true);
                 dispose();
            }            
            
            if(!user.equals(usuario) || !pass.equals(contraseña)){
                showMessageDialog(null,"EL Nombre de Usuario o Contraseña son INCORRECTOS");
                txtUsuario.setText("");
                txtContraseña.setText("");
            }
            
            if(user.equals("") || pass.equals("")){
                showMessageDialog(null,"El Nombre de Usuario o Contraseña son INCORRECTOS");
                txtContraseña.setText("");
                txtUsuario.setText("");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       */
      
        
        
        
                           
        
    }//GEN-LAST:event_vamosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        REGISTRARSE_DOCENTE c = new REGISTRARSE_DOCENTE();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vamosMousePressed
        String usuario = txtUsuario.getText();
        String contra = txtContraseña.getText();
         if(usuario.isEmpty()){
             showMessageDialog(this, "Campo de Usuario vacío");
             return;
         }
         if(contra.isEmpty()){
             showMessageDialog(this, "Campo de Contraseña vacío");
             return;
         }
         boolean login = Docente.login(usuario, contra);
         if(!login){
             showMessageDialog(this, "Usuario no valido");
             return;
         }
         temas_principales dashboard = new temas_principales();
         dashboard.setVisible(true);
         dispose();
    }//GEN-LAST:event_vamosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton propietario;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JButton vamos;
    // End of variables declaration//GEN-END:variables
}
