/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRINCIPALES;

//import DOCENTES.Conexion2;
import java.awt.Dimension;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Anahí Zepeda
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
   
     //Conexion2 Conect;
     
    public principal() {
        initComponents();
        this.setSize(new Dimension(500, 500));
        setLocationRelativeTo(null);
        dispose();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        vamos = new javax.swing.JButton();
        propietario = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel4.setText("Secundaria. 1°");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 390, 253, 48);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel5.setText("ENCICLOPEDIA ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 140, 287, 48);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel6.setText("MATEMATICAS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 200, 290, 60);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel1.setText("de las");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 170, 110, 48);

        vamos.setBackground(new java.awt.Color(102, 0, 102));
        vamos.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        vamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/inicia chico.png"))); // NOI18N
        vamos.setText("VAMOS");
        vamos.setBorderPainted(false);
        vamos.setContentAreaFilled(false);
        vamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vamos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/inicia chico.png"))); // NOI18N
        vamos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/inicia grande.png"))); // NOI18N
        vamos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/inicia grande.png"))); // NOI18N
        vamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vamosActionPerformed(evt);
            }
        });
        getContentPane().add(vamos);
        vamos.setBounds(180, 260, 260, 140);

        propietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/simbolo chico t.png"))); // NOI18N
        propietario.setBorderPainted(false);
        propietario.setContentAreaFilled(false);
        propietario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/simboo grande t.png"))); // NOI18N
        propietario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/simboo grande t.png"))); // NOI18N
        propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propietarioActionPerformed(evt);
            }
        });
        getContentPane().add(propietario);
        propietario.setBounds(100, 20, 150, 130);

        salir.setBackground(new java.awt.Color(102, 0, 102));
        salir.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir chico.png"))); // NOI18N
        salir.setText("SALIR");
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir chico.png"))); // NOI18N
        salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir grande.png"))); // NOI18N
        salir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir grande.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(0, 270, 230, 102);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/naturaleza.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 490, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vamosActionPerformed
        //try{
            //Conect = new Conexion2();
            //System.out.println("SE CONECTO CORRECTAMENTE A LA BASE DE DATOS");
            login t= new login();
            t.setVisible(true);
            dispose();
        //}
        //catch(SQLException ex){JOptionPane.showMessageDialog(null,ex);}
    }//GEN-LAST:event_vamosActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void propietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propietarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton propietario;
    private javax.swing.JButton salir;
    private javax.swing.JButton vamos;
    // End of variables declaration//GEN-END:variables
}
