/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRINCIPALES;

import DOCENTES.mi_grupo;
import java.awt.Dimension;

/**
 *
 * @author Anahí Zepeda
 */
public class temas_principales extends javax.swing.JFrame {

    /**
     * Creates new form temas_principales
     */
    public temas_principales() {
        initComponents();
        this.setSize(new Dimension(620, 430));
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boton_Algebra = new javax.swing.JButton();
        boton_Aritmetica = new javax.swing.JButton();
        boton_Geometria = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel5.setText("ENCICLOPEDIA ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 170, 210, 33);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setText("de las");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 190, 110, 60);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel4.setText("MATEMATICAS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 240, 200, 48);

        boton_Algebra.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        boton_Algebra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/algebra min.png"))); // NOI18N
        boton_Algebra.setText("ALGEBRA");
        boton_Algebra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton_Algebra.setBorderPainted(false);
        boton_Algebra.setContentAreaFilled(false);
        boton_Algebra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_Algebra.setFocusPainted(false);
        boton_Algebra.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/algebra max.png"))); // NOI18N
        boton_Algebra.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/algebra max max.png"))); // NOI18N
        boton_Algebra.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/algebra max max.png"))); // NOI18N
        boton_Algebra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AlgebraActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Algebra);
        boton_Algebra.setBounds(350, 130, 240, 100);

        boton_Aritmetica.setBackground(new java.awt.Color(255, 255, 255));
        boton_Aritmetica.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        boton_Aritmetica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/aritmetica min.png"))); // NOI18N
        boton_Aritmetica.setText("ARITMETICA");
        boton_Aritmetica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton_Aritmetica.setBorderPainted(false);
        boton_Aritmetica.setContentAreaFilled(false);
        boton_Aritmetica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_Aritmetica.setFocusPainted(false);
        boton_Aritmetica.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/aritmetica max.png"))); // NOI18N
        boton_Aritmetica.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/aritmetica max max.png"))); // NOI18N
        boton_Aritmetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AritmeticaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Aritmetica);
        boton_Aritmetica.setBounds(330, 20, 270, 110);

        boton_Geometria.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        boton_Geometria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/geometria min.png"))); // NOI18N
        boton_Geometria.setText("GEOMETRIA");
        boton_Geometria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton_Geometria.setBorderPainted(false);
        boton_Geometria.setContentAreaFilled(false);
        boton_Geometria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_Geometria.setFocusPainted(false);
        boton_Geometria.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/geometria max.png"))); // NOI18N
        boton_Geometria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/geometria max max.png"))); // NOI18N
        boton_Geometria.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/geometria max max.png"))); // NOI18N
        boton_Geometria.setSelected(true);
        boton_Geometria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GeometriaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Geometria);
        boton_Geometria.setBounds(350, 240, 250, 110);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel6.setText("Secundaria. 1°");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 330, 280, 48);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir chico.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir chico.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/salir grande.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 290, 110, 110);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/simbolo chico t.png"))); // NOI18N
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButton17);
        jButton17.setBounds(160, 60, 120, 100);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/USER.png"))); // NOI18N
        jButton2.setText("IR A MI GRUPO");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/USER.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/USER3.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/USER3.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 10, 240, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pregunta chico.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pregunta grande.png"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pregunta grande.png"))); // NOI18N
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pregunta chico.png"))); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 140, 100, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/follaje-colgando-desenfoque-fondo-naturaleza-verde-espacio-texto_43300-390.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -6, 610, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_AlgebraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AlgebraActionPerformed
        /*algebra2 a = new algebra2();
        a.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_boton_AlgebraActionPerformed

    private void boton_AritmeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AritmeticaActionPerformed
       /* Aritmetica a = new Aritmetica();
        a.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_boton_AritmeticaActionPerformed

    private void boton_GeometriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GeometriaActionPerformed
        /*Geometria g = new Geometria();
        g.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_boton_GeometriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mi_grupo g = new mi_grupo();
        g.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Algebra;
    private javax.swing.JButton boton_Aritmetica;
    private javax.swing.JButton boton_Geometria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
